### ISSUE TITLE
hyperparameters for state SAC

### ISSUE THREAD

**Issue by kyonofx** [MishaLaskin/rad#11]
Thank you for the wonderful work and repo!

Could you share your hyperparameters or your reference for state SAC in dm_control and OpenAI Gym environments? Thank you very much!

**Comment by HosseinSheikhi** [comment]
> Thank you for the wonderful work and repo!
> 
> Could you share your hyperparameters or your reference for state SAC in dm_control and OpenAI Gym environments? Thank you very much!

would you please share the repo of pure SAC implementation you are using. I cant find ready to go, pure SAC compatible with dm_control.

**Comment by kyonofx** [comment]
you can use this repo and set --encoder_type to something other than 'pixel'

**Comment by HosseinSheikhi** [comment]
Change to the 'pixel' will lead to creating state-based agents:
https://github.com/MishaLaskin/rad/blob/1246bfd6e716669126e12c1f02f393801e1692c1/train.py#L197

By the way encoder type could be either 'pixel' or 'identity':
https://github.com/MishaLaskin/rad/blob/1246bfd6e716669126e12c1f02f393801e1692c1/encoder.py#L125

am not quite sure by maybe eliminating this line will lead to the SAC:
https://github.com/MishaLaskin/rad/blob/1246bfd6e716669126e12c1f02f393801e1692c1/curl_sac.py#L362
any idea?

**Comment by MishaLaskin** [comment]
Yes, you need to change the encoder type to 'identity'
