### ISSUE TITLE
Fixing BibTeX?

### ISSUE THREAD

**Issue by DanielTakeshi** [MishaLaskin/rad#2]
Hi @MishaLaskin ,

Great work on this paper! Excited to read it.

Just one quick comment, it looks like the README has a BibTeX with a title that refers to your other paper:

<img width="952" alt="Screen Shot 2020-04-30 at 9 12 38 PM" src="https://user-images.githubusercontent.com/5532096/80781521-6b652e80-8b27-11ea-9923-9d03b416ea52.png">

**Comment by MishaLaskin** [comment]
fixed! thanks Daniel
