### ISSUE TITLE
Why is the encoder detached?

### ISSUE THREAD

**Issue by miriaford** [MishaLaskin/rad#4]
I might have missed something simple, but could you please kindly explain why don't you update the encoder part? 

https://github.com/MishaLaskin/rad/blob/master/curl_sac.py#L411-L413

In other SAC implementations (e.g. rlkit), the gradient back-props through the entire policy network. Thanks!

**Comment by MishaLaskin** [comment]
You still backprop from the critic, so the encoder gets gradients from Q value estimation. The only detached parts are gradients from the actor, which results in more stable policies.

**Comment by miriaford** [comment]
Thanks! Is there any literature to back this up? Or is it purely empirical?

**Comment by MishaLaskin** [comment]
afaik empirical
