### ISSUE TITLE
Tensorboard Visualization

### ISSUE THREAD

**Issue by HosseinSheikhi** [MishaLaskin/rad#6]
Thanks for sharing the code. I have just got in trouble to visualize the training process using tensorboard. I must run `tensorboard --logdir log --port 6006` in /tmp/cartpolblahblah/ folder, right? Where log folder will appear, can't find any trace?

**Comment by MishaLaskin** [comment]
yes - make sure there's a `train.log` file in there.

**Comment by HosseinSheikhi** [comment]
Don't know what's the problem, I cant visualize the log file. However, I added `summurywriter()` and went ahead with that.

**Comment by MishaLaskin** [comment]
I see, it may be a tb version issue? Closing since this seems resolved
