### ISSUE TITLE
Augmentation for state-based inputs?

### ISSUE THREAD

**Issue by TairanHe** [MishaLaskin/rad#8]
random amplitude scaling and Gaussian noise

**Comment by MishaLaskin** [comment]
@pokaxpoka is this available in your RAD codebase?

**Comment by lknownothing** [comment]
> random amplitude scaling and Gaussian noise

Hi， Can you reproduce the State-based Augmentation results? I find it even can not not convergence!

**Comment by MishaLaskin** [comment]
hey @pokaxpoka can you provide some guidance to @TairanHe for the state-based augmentation experiments?

**Comment by pokaxpoka** [comment]
Here is a link to the codebase: https://github.com/pokaxpoka/rad_openaigym !
